# Site settings
title: "HEAR Health"
email: "hello@herehealth.online"
description: "Your personal health assistant"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.herahealth.online" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
