# Site settings
theme: minima
title: Better Call Doc!
email: callme@bettercalldoc.online
description: > Stay active and healthy as long as you can!
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.bettercalldoc.online" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
