# Site settings
title: "MAIA Health"
email: "hello@maia.health"
description: "Your personal health assistant"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.maia.health" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
